# Generated by Django 4.2 on 2023-04-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0002_remove_user_address_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Chairmans',
        ),
    ]
