# Generated by Django 4.2 on 2023-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0004_rename_chairmans_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='society-member', max_length=100),
        ),
    ]
