# Generated by Django 4.2 on 2023-05-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0006_chairman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chairman',
        ),
    ]
