# Generated by Django 4.2 on 2023-05-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0011_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='vehical',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
