# Generated by Django 4.2 on 2023-05-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0012_visitor_vehical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('complain', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
