# Generated by Django 4.2 on 2023-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0014_watchman_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchman',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
