# Generated by Django 4.2 on 2023-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0016_user_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintainance', models.PositiveIntegerField()),
            ],
        ),
    ]
