# Generated by Django 4.2 on 2023-05-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0017_chairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_s.chairman')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_s.user')),
            ],
        ),
    ]
