# Generated by Django 4.2 on 2023-05-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0018_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='house',
            new_name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='watchman',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='d_s.user'),
        ),
    ]
