# Generated by Django 4.2 on 2023-05-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0019_rename_house_transaction_user_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchman',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_s.user'),
        ),
    ]
