# Generated by Django 4.2 on 2023-05-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_s', '0021_alter_watchman_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchman',
            name='house',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='d_s.user'),
        ),
    ]
